### PR TITLE
some minor cleanups and sanity checks

### PR DESCRIPTION
**Pull request by EagleCall**

### CODE REVIEW

**Comment by EagleCall** [comment]
Well, for myself (and possibly others), major animal inaccuracies make me cringe.  Minor changes or abstractions because of game mechanics and balance are fine, but doing things they really couldn't or wouldn't at all bugs me no end.  (Ugg, *why* did I have to find out that alpacas can't really be milked?  It wouldn't bug me if I didn't *know*.)  However, all that said, you're in charge here so if you insist...

Err, I'm also still working on understanding the intricacies of GitHub.  Is there a way I can just keep those changes on my version while pushing the rest to yours?  Or do I have to make a branch?

**Comment by DrZhivago1** [comment]
Yea I understand what you mean. Can be strange to see a cat hauling or the idea of getting a cup of milk from an animal. I'm trying to keep the mod mostly in-line with the original, and since there is no large call to make changes with the animals, I have no urge to do it.

I'm no master Githubber either haha. I think you'll have to make a new branch on your own fork, or make the changes and then revert them.

**Comment by EagleCall** [comment]
I guess that's fair enough.  I'll work on that, then.

**Comment by DrZhivago1** [comment]
Thanks for the help cleaning it up and the ideas!

**Pull request merged**
